parameters:
    rabbitmq.host: '%env(RABBITMQ_HOST)%'
    rabbitmq.port: '%env(int:RABBITMQ_PORT)%'
    rabbitmq.user: '%env(RABBITMQ_USER)%'
    rabbitmq.password: '%env(RABBITMQ_PASSWORD)%'
    rabbitmq.vhost: '%env(RABBITMQ_VHOST)%'
    mail.from_address: '%env(MAIL_FROM)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    monolog.formatter.json:
        class: Monolog\Formatter\JsonFormatter

    App\Monolog\TraceProcessor:
        tags:
            - { name: monolog.processor }

    App\Command\ConsumeUserEventsCommand:
        arguments:
            $host: '%rabbitmq.host%'
            $port: '%rabbitmq.port%'
            $user: '%rabbitmq.user%'
            $password: '%rabbitmq.password%'
            $vhost: '%rabbitmq.vhost%'

    App\Mail\WelcomeMailer:
        arguments:
            $fromAddress: '%mail.from_address%'
